### ISSUE TITLE
app crashed when starting todoist

### ISSUE THREAD

**Issue by glor** [ligi/FAST#117]
```
file: /data/user/0/org.ligi.faster/files/6.8-1610276445843.tracedroid
Android Version: 8.0.0
Phone Model: ???????????????
TraceDroid Version: 1.1
TraceDroid extra: 
Stacktrace: 
 java.lang.SecurityException: Permission Denial: starting Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 cmp=com.todoist/.activity.HomeActivity } from ProcessRecord{9e32620 4214:org.ligi.faster/u0a236} (pid=4214, uid=10236) not exported from uid 10095
 at android.os.Parcel.readException(Parcel.java:1943)
 at android.os.Parcel.readException(Parcel.java:1889)
 at android.app.IActivityManager$Stub$Proxy.startActivity(IActivityManager.java:4448)
 at android.app.Instrumentation.execStartActivity(Instrumentation.java:1680)
 at android.app.Activity.startActivityForResult(Activity.java:4477)
 at android.app.Activity.startActivityForResult(Activity.java:4435)
 at android.app.Activity.startActivity(Activity.java:4800)
 at android.app.Activity.startActivity(Activity.java:4768)
 at org.ligi.fast.ui.SearchActivity.a(Unknown Source:72)
 at org.ligi.fast.ui.ab.onItemClick(Unknown Source:2)
 at android.widget.AdapterView.performItemClick(AdapterView.java:318)
 at android.widget.AbsListView.performItemClick(AbsListView.java:1165)
 at android.widget.AbsListView$PerformClick.run(AbsListView.java:3160)
 at android.widget.AbsListView$3.run(AbsListView.java:4075)
 at android.os.Handler.handleCallback(Handler.java:789)
 at android.os.Handler.dispatchMessage(Handler.java:98)
 at android.os.Looper.loop(Looper.java:164)
 at android.app.ActivityThread.main(ActivityThread.java:6592)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:769)
Log: 
 0 D: Writing unhandled exception to: /data/user/0/org.ligi.faster/files/6.8-1610276445843.tracedroid
1 I: returning true
2 I: returning true
3 I: returning true
4 I: returning true
5 I: returning true
6 I: returning true
7 I: returning true
8 I: returning true
9 I: returning true
10 I: returning true
11 I: Saving package list to file
12 I: Saving package list to file
13 D: Searching Exceptions in: /data/user/0/org.ligi.faster/files
14 I: returning true
15 I: returning true
16 I: returning true
17 I: returning true
18 I: returning true
19 I: returning true
20 I: returning true
21 I: returning true
22 I: returning true
23 I: returning true
24 I: returning true
25 I: returning true
26 I: returning true
27 I: returning true
28 I: returning true
29 I: returning true
30 I: returning true
31 I: returning true
32 I: returning true
33 I: returning true
34 I: returning true
35 I: returning true
36 I: returning true
37 I: returning true
38 I: returning true
39 I: returning true
40 I: returning true
41 I: returning true
```

**Comment by glor** [comment]
seems like it disappeared after some updates
